### ISSUE TITLE
[Bug] Signaling server cannot connect to NATS on a clean Docker install

### ISSUE THREAD

**Issue by Werbnerd** [strukturag/nextcloud-spreed-signaling#1003]
Hello to the development team,

first of all, thank you for your great work on the Nextcloud Talk signaling server!

I'm trying to set up the server in my environment but have run into a persistent issue. The signaling container is unable to connect to the NATS backend, even though all tests show that the underlying network connectivity is working perfectly. I've tried to debug this for a long time and believe I have isolated a potential bug.

Here are my findings:

I have tried on multiple host environments (an existing Ubuntu 22.04 VM and a fresh Debian 12 VM on Proxmox) with the exact same result. My current setup is a clean Debian 12 VM with a fresh install of Docker and Docker Compose.

My docker-compose.yaml runs both signaling (v1.2.3) and nats (v2.10) on a shared custom bridge network:

My docker-compose.yaml:

```yaml
services:
  signaling:
    image: strukturag/nextcloud-spreed-signaling:1.2.3
    container_name: nextcloud-signaling
    restart: unless-stopped
    volumes:
      - ./server.conf:/config/server.conf:ro
    ports:
      - "8081:8080"
    depends_on:
      - nats
    networks:
      - signaling-net

  nats:
    image: nats:2.10
    container_name: nats
    restart: unless-stopped
    networks:
      - signaling-net

networks:
  signaling-net:
    driver: bridge
```

My server.conf:

```ini
[http]
listen = "0.0.0.0:8080"

[app]
[app.auth]
secret = "MY_SECRET_PASSWORD"

[nats]
servers = ["nats://nats:4222"]
```

The application log for the signaling server always shows nats: no servers available for connection.

Crucial finding:
From inside the signaling container, I can successfully resolve and connect to the nats container on the correct port:

ping nats -> 0% packet loss
nc -z -v nats 4222 -> nats (172.20.0.2:4222) open
This proves that the Docker networking, DNS, and TCP connectivity are all working perfectly. The application seems to be ignoring the configuration or is failing to connect despite a valid and proven network path.

Thank you very much for your time and any help you can provide.

Best regards,

Webnerd
