### ISSUE TITLE
More detailed information about docker compose

### ISSUE THREAD

**Issue by masterxq** [strukturag/nextcloud-spreed-signaling#411]
It could be nice if the README would contain more detailed information about how-to use docker compose with this project.

At least I think I am not using it like as intended. I always run into other issues, and I think more that 50% are not because the software is broken, but because it hard to use it as intended without documentation.

Thank you!

**Comment by PentaPaetzold** [comment]
i got that problem too and managed to get it working half way.
Maybe we can find out, how it works.

Currently i added:
```
# nextcloud coturn
# Be sure to open 3478/tcp+udp on Firewall if needed
  coturn:
    image: coturn/coturn:latest
    command:
      - "--realm"
      - "signaling.your.site"
#Does not make sense to use both, but either one of lt-cred-mech OR use-auth-secret
#      - "--lt-cred-mech"
      - "--use-auth-secret"
      - "--static-auth-secret"
      - "thisisyourrandomcoturnsecret"
      - "--no-stdout-log"
      - "--log-file"
      - "stdout"
      - "--stale-nonce=600"
      - "--fingerprint"
      - "--no-software-attribute"
      - "--no-multicast-peers"
    volumes:
      - coturn:/var/lib/coturn
    restart: unless-stopped
    ports:
      - 3478:3478
    networks:
      - proxy-tier

# Janus Webrtc Gatway
  janus:
    image: 'canyan/janus-gateway:0.10.7'
    command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus", "--stun-server=coturn:3478"]
#    expose:
#      - 8080
#    ports:
#      - "8088:8088"
#      - "8089:8089"
#      - "8889:8889"
#      - "8000:8000"
#      - "7088:7088"
#      - "7089:7089"
#    volumes:
#      - "./etc/janus/janus.jcfg:/usr/local/etc/janus/janus.jcfg"
#      - "./etc/janus/janus.eventhandler.sampleevh.jcfg:/usr/local/etc/janus/janus.eventhandler.sampleevh.jcfg"
    restart: unless-stopped
    networks:
      - proxy-tier

# Nextcloud Signaling Webserver
# Docs: https://github.com/strukturag/nextcloud-spreed-signaling/tree/master/docker
  spreedbackend:
    platform: linux/amd64
    image: strukturag/nextcloud-spreed-signaling:master
    restart: unless-stopped
    environment:
      - HTTP_LISTEN=spreedbackend:8080
      - COUNTRY=DE
      - HASH_KEY=yourhashkey
      - BLOCK_KEY=yourblockkey
      - INTERNAL_SHARED_SECRET_KEY=yoursharedsecret
      - BACKENDS=site1
      - BACKEND_SITE1_URL=https://nextcloud.your.site
      - BACKEND_SITE1_SHARED_SECRET=yoursharedsecret
# This is currently my problem:
      - USE_JANUS=0
# what should work is this:
#      - USE_JANUS=1
#      - JANUS_URL=ws://janus:8088
# No need for nats when only one Backend?
#      - NATS_URL=nats://nats:4222
# Turn
      - TURN_SERVERS=turn:coturn:3478?transport=udp,turn:coturn:3478?transport=tcp
      - TURN_API_KEY=thisisyourrandomcoturnsecret
      - TURN_SECRET=thisisyourrandomcoturnsecret
# Nginx- Proxy vhost
      - VIRTUAL_HOST=signaling.your.site
      - LETSENCRYPT_HOST=signaling.your.site
      - LETSENCRYPT_EMAIL=admin@your.site
      - VIRTUAL_PORT=8080
    networks:
      - proxy-tier
    depends_on:
      - coturn
      - janus
````
Adjust your networks or delete mine.
With that setup you can use signaling.your.site:3478 as stun and turn-server using the secret of coturn.
Than add hpb to nextcloud: https://signaling.your.site given the shared secret.

That basically would do - but would not use janus mcu. So my problems are:
When enabling janus in spreed - i get errors invalid handshake in spreed with janus and it won't work.

Maybe anyone here that can help with setting up janus that way to work with spreed without build it from source?

**Comment by PentaPaetzold** [comment]
@fancycode Hi Joachim, as a maintainer of nc-spreed: what would you think of using build images for janus and spreed as proposed [above](https://github.com/strukturag/nextcloud-spreed-signaling/issues/411#issuecomment-1589331096)?
Imo this would reduce the need to build those tools and reduce maintanance of this repo for janus.

If you agree, i could implement my changes into a pull request for your repo.

**Comment by dounoit** [comment]
> Update: Got it working. Needed to use ws at 8188 of janus and option full-trickle. Updated code to fit.
> 
> i added:
> 
> ```
> # nextcloud coturn
> # Be sure to open 3478/tcp+udp on Firewall if needed
>   coturn:
>     image: coturn/coturn:latest
>     command:
>       - "--realm"
>       - "signaling.your.site"
> #Does not make sense to use both, but either one of lt-cred-mech OR use-auth-secret
> #      - "--lt-cred-mech"
>       - "--use-auth-secret"
>       - "--static-auth-secret"
>       - "thisisyourrandomcoturnsecret"
>       - "--no-stdout-log"
>       - "--log-file"
>       - "stdout"
>       - "--stale-nonce=600"
>       - "--fingerprint"
>       - "--no-software-attribute"
>       - "--no-multicast-peers"
>     volumes:
>       - coturn:/var/lib/coturn
>     restart: unless-stopped
>     ports:
>       - 3478:3478
>     networks:
>       - proxy-tier
> 
> # Janus Webrtc Gatway
>   janus:
>     image: 'canyan/janus-gateway:0.10.7'
>     command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus", "--stun-server=coturn:3478", "--full-trickle"]
>     restart: unless-stopped
>     networks:
>       - proxy-tier
> 
> # Nextcloud Signaling Webserver
> # Docs: https://github.com/strukturag/nextcloud-spreed-signaling/tree/master/docker
>   spreedbackend:
>     platform: linux/amd64
>     image: strukturag/nextcloud-spreed-signaling:master
>     restart: unless-stopped
>     environment:
>       - HTTP_LISTEN=spreedbackend:8080
>       - COUNTRY=DE
>       - HASH_KEY=yourhashkey
>       - BLOCK_KEY=yourblockkey
>       - INTERNAL_SHARED_SECRET_KEY=yoursharedsecret
>       - BACKENDS=site1
>       - BACKEND_SITE1_URL=https://nextcloud.your.site
>       - BACKEND_SITE1_SHARED_SECRET=yoursharedsecret
> # Janus/WebRTC
>       - USE_JANUS=1
>       - JANUS_URL=ws://janus:8188
> # No need for nats when only one Spreed-Server
> #      - NATS_URL=nats://nats:4222
> # Turn
>       - TURN_SERVERS=turn:coturn:3478?transport=udp,turn:coturn:3478?transport=tcp
>       - TURN_API_KEY=thisisyourrandomcoturnsecret
>       - TURN_SECRET=thisisyourrandomcoturnsecret
> # Nginx- Proxy vhost
>       - VIRTUAL_HOST=signaling.your.site
>       - LETSENCRYPT_HOST=signaling.your.site
>       - LETSENCRYPT_EMAIL=admin@your.site
>       - VIRTUAL_PORT=8080
>     networks:
>       - proxy-tier
>     depends_on:
>       - coturn
>       - janus
> ```
> 
> Adjust your networks or delete mine. And add a coturn- volume. With that setup you can use signaling.your.site:3478 as stun and turn-server using the secret of coturn in Nextcloud- Talk- Setup. Than add hpb to nextcloud: https://signaling.your.site given the shared secret.
> 
> Problems solved. I would appreachiate this to see described as an alternative to the current setup, where janus and spreed needs to be compiled on the client (which would not work for me).

thank you so much for this example. I've been trying to get this runnig in docker desparately. I've tried so many different options. I haven't tested your standalone docker-compose.yaml yet. I did convert and deploy it for my docker swarm cluster. I've been able to pinpoint the issue to the spreedbackend server. the port 8080 acts odd. i have to make it listen to ip localhost:8080 instead of spreedbackend:8080- else it says its already listening.

# current config
```
# Nextcloud Signaling Webserver
  # Docs: https://github.com/strukturag/nextcloud-spreed-signaling/tree/master/docker
  spreedbackend:
    image: strukturag/nextcloud-spreed-signaling:master
    ports:
      - {target: 8080, published: 8080, mode: host, protocol: tcp}
      - {target: 8080, published: 8080, mode: host, protocol: udp}
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.labels.node==node1"

    environment:
      - HTTP_LISTEN=localhost:8080
      #- HTTP_LISTEN=spreedbackend:8080
      - COUNTRY=US
      - HASH_KEY=dddddddddddddddddddd==
      - BLOCK_KEY=eeeeeeeeeeeeeeeeeeee=
      - INTERNAL_SHARED_SECRET_KEY=ccccccccccccccccccccccc
      - BACKENDS=site1
      - BACKEND_SITE1_URL=https://nextcloud.some.url.tld
      - BACKEND_SITE1_SHARED_SECRET=bbbbbbbbbbbbbb
      # Janus/WebRTC
      - USE_JANUS=1
      - JANUS_URL=ws://janus:8188
      # No need for nats when only one Spreed-Server
      #      - NATS_URL=nats://nats:4222
      # Turn
      - TURN_SERVERS=turn:coturn:3478?transport=udp,turn:coturn:3478?transport=tcp
      - TURN_API_KEY=aaaaaaaaaaaa
      - TURN_SECRET=bbbbbbbbbbbbbb
      # Nginx- Proxy vhost
      - VIRTUAL_HOST=signaling.some.url.tld
      - LETSENCRYPT_HOST=signaling.some.url.tld
      - LETSENCRYPT_EMAIL=admin@your.site
      - VIRTUAL_PORT=8080

    networks:
      - holospreed-signaling
```

please help me with my troubleshooting- i could use another pair of eyes- am i missing how this is suppose to be behaving / tested? I would expect the welcome string when i execute this inside the container - this testing is with host mode port enabled:

```
b05f468ea31a:/$ netstat -na |grep 8080
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      
b05f468ea31a:/$ wget  http://localhost:8080/standalone-signaling/api/v1/welcome
Connecting to localhost:8080 (127.0.0.1:8080)
wget: server returned error: HTTP/1.1 404 Not Found
b05f468ea31a:/$ wget  http://localhost:8080/api/v1/welcome
Connecting to localhost:8080 (127.0.0.1:8080)
wget: can't open 'welcome': Permission denied
```

since i have this listening on the host too - i tried it on the docker host as well:

```
dockerhost$ wget  http://localhost:8080/standalone-signaling/api/v1/welcome
--2024-03-05 15:54:34--  http://localhost:8080/standalone-signaling/api/v1/welcome
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

dockerhost$ wget  http://localhost:8080/api/v1/welcome
--2024-03-05 15:56:24--  http://localhost:8080/api/v1/welcome
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.
```


## i then removed the host mode listening port and listens on localhost:8080
    environment:
      - HTTP_LISTEN=localhost:8080

### inside the spreedbackend container

```
f44d55587e5a:/$ netstat -na |grep 8080
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      

f44d55587e5a:/$ wget  http://localhost:8080/standalone-signaling/api/v1/welcome
Connecting to localhost:8080 (127.0.0.1:8080)
wget: server returned error: HTTP/1.1 404 Not Found

f44d55587e5a:/$ wget  http://localhost:8080/api/v1/welcome
Connecting to localhost:8080 (127.0.0.1:8080)
wget: can't open 'welcome': Permission denied

```
### from the nginx container in docker swarm on the same network (the resolving ip is incorrect due to docker dns-ip mapping)

```
wget  http://spreedbackend:8080/api/v1/welcome
root@2fe7949918b6:/# wget  http://spreedbackend:8080/standalone-signaling/api/v1/welcome
Connecting to spreedbackend:8080 (172.16.38.250:8080)
wget: can't connect to remote host (172.16.38.250): Connection refused

root@2fe7949918b6:/# wget  http://spreedbackend:8080/api/v1/welcome
Connecting to spreedbackend:8080 (172.16.38.250:8080)
wget: can't connect to remote host (172.16.38.250): Connection refused
```
### inside the spreedbackend container- regarding the ip allocation to to the swarm container - i read something about this being an issue assigning dns name to n-1 for container ip - im less worried about this atm:

inside spreedbackend container:
```
f44d55587e5a:/$ ip a
28634: eth0@if28635: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1424 qdisc noqueue state UP 
    link/ether 02:42:ac:10:26:fb brd ff:ff:ff:ff:ff:ff
    inet 172.16.38.251/24 brd 172.16.38.255 scope global eth0
```

### this is from the nginx container using the real ip of the spreedbackend container - i want to focus on the spreedbackend working before working on this weird docker swarm behavior - im just adding this for thoroughness: 
```
root@2fe7949918b6:/# wget  http://172.16.38.251:8080/standalone-signaling/api/v1/welcome
Connecting to 172.16.38.251:8080 (172.16.38.251:8080)
wget: can't connect to remote host (172.16.38.251): Connection refused

root@2fe7949918b6:/# wget  http://172.16.38.251:8080/api/v1/welcome
Connecting to 172.16.38.251:8080 (172.16.38.251:8080)
wget: can't connect to remote host (172.16.38.251): Connection refused
```

i think im zeroing in on the problem but need help getting this across the line- i look forward to sharing my work too in hopes of saving someone a weekend and days of working on this ;-) thank you so much for your work friend!
-chefboyrdave2.1 aka daveK
