### ISSUE TITLE
main.go:187: Could not create hub: could not parse IP secret/url

### ISSUE THREAD

**Issue by SystemKeeper** [strukturag/nextcloud-spreed-signaling#607]
After updating from version 1.1.3 to 1.2.1 (also happens with 1.2.0) the signaling server (docker image) is no longer able to start:

```
hpb-docker-signaling-1  | Preparing signaling server configuration in /config/server.conf ...
hpb-docker-signaling-1  | Starting signaling server with /config/server.conf ...
hpb-docker-signaling-1  | main.go:133: Starting up version 1.2.0/go1.21.3 as pid 1
hpb-docker-signaling-1  | main.go:142: Using a maximum of 12 CPUs
hpb-docker-signaling-1  | natsclient.go:73: Using internal NATS loopback client
hpb-docker-signaling-1  | grpc_common.go:167: WARNING: No GRPC server certificate and/or key configured, running unencrypted
hpb-docker-signaling-1  | grpc_common.go:169: WARNING: No GRPC CA configured, expecting unencrypted connections
hpb-docker-signaling-1  | backend_storage_static.go:72: Backend default added for https://.../
hpb-docker-signaling-1  | hub.go:202: Using a maximum of 8 concurrent backend connections per host
hpb-docker-signaling-1  | hub.go:209: Using a timeout of 10s for backend connections
hpb-docker-signaling-1  | hub.go:262: Not using GeoIP database
hpb-docker-signaling-1  | main.go:187: Could not create hub: could not parse IP secret
hpb-docker-signaling-1 exited with code 1
hpb-docker-signaling-1  | main.go:133: Starting up version 1.2.0/go1.21.3 as pid 1
hpb-docker-signaling-1  | main.go:142: Using a maximum of 12 CPUs
hpb-docker-signaling-1  | natsclient.go:73: Using internal NATS loopback client
hpb-docker-signaling-1  | grpc_common.go:167: WARNING: No GRPC server certificate and/or key configured, running unencrypted
hpb-docker-signaling-1  | grpc_common.go:169: WARNING: No GRPC CA configured, expecting unencrypted connections
hpb-docker-signaling-1  | backend_storage_static.go:72: Backend default added for https://.../
hpb-docker-signaling-1  | hub.go:202: Using a maximum of 8 concurrent backend connections per host
hpb-docker-signaling-1  | hub.go:209: Using a timeout of 10s for backend connections
hpb-docker-signaling-1  | hub.go:262: Not using GeoIP database
hpb-docker-signaling-1  | main.go:187: Could not create hub: could not parse IP url
```

The compose file looks like this:

```
version: '3'

services:
  signaling:
    image: strukturag/nextcloud-spreed-signaling:1.2.0
    network_mode: host
    restart: unless-stopped
    environment:
      - HTTP_LISTEN=172.30.150.2:8080
      - HASH_KEY=1234...
      - BLOCK_KEY=1234...
      - INTERNAL_SHARED_SECRET_KEY=1234...
      - BACKENDS=default
      - BACKEND_DEFAULT_URL=https://...
      - BACKEND_DEFAULT_SHARED_SECRET=1234....
      - USE_JANUS=1
      - JANUS_URL=ws://127.0.0.1:8188
```

I assume the problem is this PR https://github.com/strukturag/nextcloud-spreed-signaling/pull/532. The problems seems to come from the fact that the backends are added to the end of the file (when configured via docker) and the fact that I called the backend "default" ?! If I use a different name it seems to work...
