### ISSUE TITLE
Which ports need to be forwarded ?

### ISSUE THREAD

**Issue by schklom** [strukturag/nextcloud-spreed-signaling#85]
Hi,

1. Thank you so much for sharing this amazing project ! :D
2. I want to run this along with Nextcloud Talk on my Raspberry Pi via Docker.
I'm not going to forward all ports from my router to the Raspberry Pi. Therefore, could you tell me which ports are required for this to work ?
Putting everything in `network_mode: host` just makes it difficult to know what's happening with ports. I have no idea which port should be opened to the Internet, and I am definitely not going to open up all ports on my router.

Would someone please explain how this setup works ?

Many thanks to whoever answers :)

**Comment by Lumrenion** [comment]
I like to keep the docker networking clean and have been struggling with this too. But it seems, all video conference docker configurations, like for JITSI, BigBlueButton and Talk, seem to use `network_mode: host`. 
This repository was helpful: https://github.com/lnobach/nctalk-backend-cloud-config

Previously, for coturn I used port range `49160-49200:49160-49200/udp` as suggested in lnobach's repository. That worked fine in chrome and safari as well as the TALK app for iOS. But Firefox did not receive audio and video from remote participants. Other participants did receive audio and video from firefox users. I tried switching to port range `49152-65535:49152-65535/udp`, but docker-compose gave me a timeout when I tried to start or remove the container. The reason seems to be that docker performs badly forwarding wide port ranges which is why I switched to `network_mode: host` for coturn.

Notice, I use a Traefik reverse proxy which forwards port 80 and 443 to the internal port 8080 in the speedbackend.

Now I am not sure, If I should switch all services to `network_mode: host` or if the HPB works as intended with below configuration, or if it is indeed better to use `network_mode: host` for all spreed related containers. It does work with 2 participants, I did not test it with more yet. I noticed, that I cannot select `turns` in my TURN-Server configuration in the nextcloud admin area. It only works with `turn`.

``` yaml
  spreedbackend:
   [...]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud_hpb.rule=Host(`signaling.example.com`)"
      - "traefik.http.routers.nextcloud_hpb.tls.certresolver=tlschallenge"
      - "traefik.http.routers.nextcloud_hpb.middlewares=traefik-headers,spreed_headers,spreed_location"
      - "traefik.http.services.nextcloud_hpb.loadbalancer.server.port=8080"
      - "traefik.http.routers.nextcloud_hpb.entrypoints=websecure"
      - "traefik.http.middlewares.spreed_location.stripprefix.prefixes=/standalone-signaling/"
      - "traefik.http.middlewares.spreed_headers.headers.customRequestHeaders.X-Forwarded-Proto=https"
    networks:
      - traefik_proxy
      - signaling

  nats:
    [...]
    networks:
      - signaling
    expose:
      - '4222'

  janus:
    [...]
    networks:
      - signaling
    expose:
      - '8188'
    ports:
      - "20000-20100:20000-20100/udp"

  coturn:
    [...]
# coturn uses many udp ports but docker performs badly with port forwarding of wide port ranges. The recommended way is to use network_mode: host
# see https://github.com/instrumentisto/coturn-docker-image#why-so-many-ports-opened
    network_mode: host
#    networks:
#      - signaling
#    ports:
#      - 3478:3478
#      - 3478:3478/udp
#      - 5349:5349
#      - 5349:5349/udp
#      - "49160-49200:49160-49200/udp"
```
